tooltip:
  max:
    row: 12
    col: 10
  sep: "â”‚"
  title:
    color: "#ffafaf"
    weight: bold
    underline: double
  row_name:
    color: "#ffffaf"
  col_name:
    color: "#afffaf"
  word:
    clip: 15
  text:
    clip: 78

IO:
  tip_type: disks + pids

processor:
  # lowest: $ echo "100/$(nproc)" | bc
  tip_type: processors + pids

memory:
  tip_type: device + pids

temperature:
  ambient: 27  # Temperature in degrees Celsius

netcheck:
  internet: 8.8.8.8  # Google's DNS as an indicator of connection to internet

netio:
  ignore_below: 1024  # [= 1kB/s] Ignore below this speed (bytes/s)
